SRCS+=	cli/cmd_about.cpp		\
	cli/cmd_config.cpp		\
	cli/cmd_db_exec.cpp		\
	cli/cmd_db_migrate.cpp		\
	cli/cmd_debug.cpp		\
	cli/cmd_help.cpp		\
	cli/cmd_list.cpp		\
	cli/cmd_report.cpp		\
	cli/cmd_report_html.cpp		\
	cli/cmd_report_junit.cpp	\
	cli/cmd_test.cpp		\
	cli/common.cpp			\
	cli/config.cpp			\
	cli/main.cpp
