SRCS+=	engine/atf.cpp			\
	engine/atf_list.cpp		\
	engine/atf_result.cpp		\
	engine/config.cpp		\
	engine/exceptions.cpp		\
	engine/filters.cpp		\
	engine/kyuafile.cpp		\
	engine/plain.cpp		\
	engine/requirements.cpp		\
	engine/scanner.cpp		\
	engine/tap.cpp			\
	engine/tap_parser.cpp		\
	engine/scheduler.cpp
