.PATH: ${KYUA_SRCDIR}/store

SRCS+=	store/dbtypes.cpp		\
	store/exceptions.cpp		\
	store/layout.cpp		\
	store/metadata.cpp		\
	store/migrate.cpp		\
	store/read_backend.cpp		\
	store/read_transaction.cpp	\
	store/write_backend.cpp		\
	store/write_transaction.cpp
